----------------------- 
 PROTECTED FILE 
-----------------------

DON'T EVER MOVE THIS FILE!
IF YOU MOVE THIS FILE, ENTRANCE CREATOR WILL NOT WORK!
THIS FILE IS PROTECTED, YOU SHOULDN'T EVEN READ THIS FILE IN ANY CURCIUMSTANCES!
IF YOU READ THIS, IT MEANS THAT YOU PROBABLY CHANGED CHMOD OF FILE!

----------------------- 
 PROTECTED FILE 
-----------------------
